### ISSUE TITLE
NBA API headers change

### ISSUE THREAD

**Issue by delt87** [ccagrawal/nbaTools#1]
Yesterday I tried running the `GetGameLogs` function and in return I did not get an output (same thing today).  The function just hangs for a while and does not return the expected game logs.  I've been following the same issue as reported in the nba_api for Python and the issues seems to be related to the fact that NBA API headers have changed (again).  I manually added the following fields to the headers and the function returned the expected game logs:

```
    'x-nba-stats-origin' = 'stats',
    'x-nba-stats-token' = 'true'
```

**Working NBA headers:**
```
  'NBA' = list(
    'Accept' = 'application/json, text/plain, */*',
    'Accept-Language' = 'en-US,en;q=0.8,af;q=0.6',
    'Referer' = 'http://stats.nba.com/%referer%/',
    'User-Agent' = paste('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)',
                         'AppleWebKit/537.36 (KHTML, like Gecko)',
                         'Chrome/67.0.3396.99 Safari/537.36'),
    'x-nba-stats-origin' = 'stats',
    'x-nba-stats-token' = 'true'
  ) 
```
I'm not familiar with how GitHub works as far as making changes to other people's work. I figured if I made you aware of the change in the headers and the fix it would be easy for you to update the package on your end with the new headers.

**Comment by ccagrawal** [comment]
Thanks for finding this. I made the change, and it works for me. Let me know if you still have this issue.

**Comment by delt87** [comment]
Works perfect.  Thanks for making the change so quickly.
